amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "<robot_namespace>/base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "<robot_namespace>/map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 1000
    min_particles: 500
    odom_frame_id: "<robot_namespace>/odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: "/<robot_namespace>/scan"

bt_navigator:
  ros__parameters:
    global_frame: "<robot_namespace>/map"
    robot_base_frame: "<robot_namespace>/base_footprint"
    odom_topic: "/<robot_namespace>/odom"   # ← クォート推奨
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: []

    error_code_names:
      - compute_path_error_code
      - follow_path_error_code

controller_server:
  ros__parameters:
    # controller_frequency: 20.0
    controller_frequency: 20.0
    # costmap_update_timeout: 0.30
    costmap_update_timeout: 0.50
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"] # ロボットがちゃんと進んでいるかを判定, 停滞を検出
    goal_checker_plugins: ["general_goal_checker"] # ロボットがゴールに到着したかどうか判定
    controller_plugins: ["FollowPath"]             # 経路計画アルゴリズム
    use_realtime_priority: false

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5  # ゴール許容範囲と同じに設定
      movement_time_allowance: 60.0  # タイムアウトを延長
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 3.15 # 向きを考慮しない
    FollowPath:
      # plugin: "nav2_mppi_controller::MPPIController"
      # plugin: "nav2_pure_pursuit_controlle0r::PurePursuitController"
      plugin: "nav2_rl_controller::RLController"
      # plugin: "dwb_core::DWBLocalPlanner"

      # # Pure Pursuit Controller Parameters
      # desired_linear_vel: 1.0
      # lookahead_dist: 0.5
      # max_angular_vel: 1.2
      # transform_tolerance: 1.0

      # # MPPI Controller Parameters
      # time_steps: 56
      # model_dt: 0.05
      # batch_size: 2000
      # ax_max: 3.0
      # ax_min: -3.0
      # ay_max: 3.0
      # ay_min: -3.0
      # az_max: 3.5
      # vx_std: 0.2
      # vy_std: 0.2
      # wz_std: 0.4
      # vx_max: 0.5
      # vx_min: -0.35
      # vy_max: 0.5
      # wz_max: 1.9
      # iteration_count: 1
      # prune_distance: 1.7
      # transform_tolerance: 2.0
      # temperature: 0.3
      # gamma: 0.015
      # motion_model: "DiffDrive"
      # visualize: true
      # regenerate_noises: true
      # TrajectoryVisualizer:
      #   trajectory_step: 5
      #   time_step: 3
      # AckermannConstraints:
      #   min_turning_r: 0.2
      # critics: [
      #   "ConstraintCritic", "CostCritic", "GoalCritic",
      #   "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
      #   "PathAngleCritic", "PreferForwardCritic"]
      # ConstraintCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 4.0
      # GoalCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 5.0
      #   threshold_to_consider: 1.4
      # GoalAngleCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 3.0
      #   threshold_to_consider: 0.5
      # PreferForwardCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 5.0
      #   threshold_to_consider: 0.5
      # CostCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 3.81
      #   near_collision_cost: 253
      #   critical_cost: 300.0
      #   consider_footprint: false
      #   collision_cost: 1000000.0
      #   near_goal_distance: 1.0
      #   trajectory_point_step: 2
      # PathAlignCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 14.0
      #   max_path_occupancy_ratio: 0.05
      #   trajectory_point_step: 4
      #   threshold_to_consider: 0.5
      #   offset_from_furthest: 20
      #   use_path_orientations: false
      # PathFollowCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 5.0
      #   offset_from_furthest: 5
      #   threshold_to_consider: 1.4
      # PathAngleCritic:
      #   enabled: true
      #   cost_power: 1
      #   cost_weight: 2.0
      #   offset_from_furthest: 4
      #   threshold_to_consider: 0.5
      #   max_angle_to_furthest: 1.0
      #   mode: 0
      # # TwirlingCritic:
      # #   enabled: true
      # #   twirling_cost_power: 1
      # #   twirling_cost_weight: 10.0

      debug_trajectory_details: True
      min_vel_x: -0.35
      min_vel_y: 0.0
      max_vel_x: 0.5
      max_vel_y: 0.0
      max_vel_theta: 1.9
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_speed_theta: 0.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      xy_goal_tolerance: 0.25
      path_length_tolerance: 1.0
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      limit_vel_cmd_in_traj: False
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 10.0
      global_frame: "<robot_namespace>/odom"
      robot_base_frame: "<robot_namespace>/base_footprint"
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.1
      robot_radius: 0.22
      plugins: ["voxel_layer", "inflation_layer"]
      # plugins: ["voxel_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.70
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /<robot_namespace>/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "<robot_namespace>/map"
      robot_base_frame: "<robot_namespace>/base_footprint"
      robot_radius: 0.22
      resolution: 0.1
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      # plugins: ["static_layer", "inflation_layer"]
      # plugins: ["static_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /<robot_namespace>/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.7
      always_send_full_costmap: True
# マップ配信にも名前空間を適用するためパラメータ追加
map_server:
  ros__parameters:
    use_sim_time: True
    frame_id: "<robot_namespace>/map"

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 5.0
#     planner_plugins: ["GridBased"]
#     costmap_update_timeout: 1.0
#     GridBased:
#       plugin: "nav2_navfn_planner::NavfnPlanner"
#       tolerance: 0.5
#       use_astar: true
#       allow_unknown: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0 # 5.0から1.0に下げてCPU負荷を劇的に軽減
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      tolerance: 1.0          # 0.5から1.0へ拡大（パスが見つかりやすくなる）
      use_costmap_weights: true
      maximum_iterations: 1000000
      max_on_approach_iterations: 1000
      allow_unknown: true
      max_planning_time: 2.0  # タイムアウトを設定してシステム全体のフリーズを防ぐ
      cost_travel_multiplier: 2.0

# planner_server:
#   ros__parameters:
#     expected_planner_frequency: 10.0
#     planner_plugins: ["GridBased"]
#     costmap_update_timeout: 1.0
#     GridBased:
#       plugin: "nav2_smac_planner::SmacPlannerHybrid"  # ← 変更
      
#       # 基本設定
#       tolerance: 0.5
#       downsample_costmap: false
#       allow_unknown: true
#       max_iterations: 2000000
#       max_planning_time: 10.0
      
#       # 運動学的パラメータ（ロボットに合わせて調整）
#       motion_model_for_search: "DUBIN"       # 前進のみ
#       # motion_model_for_search: "REEDS_SHEPP"  # 後退可能
#       minimum_turning_radius: 0.33            # ロボットの最小回転半径
#       angle_quantization_bins: 72            # 角度分解能（5度）
      
#       # スムージング
#       smooth_path: true
      
#       # コスト調整
#       cost_travel_multiplier: 2.0
#       cost_penalty: 3.0
#       retrospective_penalty: 0.015

# smoother_server:
#   ros__parameters:
#     smoother_plugins: ["simple_smoother"]
#     simple_smoother:
#       plugin: "nav2_smoother::SimpleSmoother"
#       tolerance: 1.0e-10
#       max_its: 1000
#       do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: /<robot_namespace>/local_costmap/costmap_raw
    global_costmap_topic: /<robot_namespace>/global_costmap/costmap_raw
    local_footprint_topic: /<robot_namespace>/local_costmap/published_footprint
    global_footprint_topic: /<robot_namespace>/global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: "<robot_namespace>/odom"
    global_frame: "<robot_namespace>/map"
    robot_base_frame: "<robot_namespace>/base_footprint"
    transform_tolerance: 2.0
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

# waypoint_follower:
#   ros__parameters:
#     loop_rate: 20
#     stop_on_failure: false
#     action_server_result_timeout: 900.0
#     waypoint_task_executor_plugin: "wait_at_waypoint"
#     wait_at_waypoint:
#       plugin: "nav2_waypoint_follower::WaitAtWaypoint"
#       enabled: True
#       waypoint_pause_duration: 200

# route_server:  # Not available - commented out
#   ros__parameters:
#     # The graph_filepath does not need to be specified since it going to be set by defaults in launch.
#     # If you'd rather set it in the yaml, remove the default "graph" value in the launch file(s).
#     # file & provide full path to map below. If graph config or launch default is provided, it is used
#     # graph_filepath: $(find-pkg-share nav2_route)/graphs/aws_graph.geojson
#     boundary_radius_to_achieve_node: 1.0
#     radius_to_achieve_node: 2.0
#     smooth_corners: true
#     operations: ["AdjustSpeedLimit", "ReroutingService", "CollisionMonitor"]
#     ReroutingService:
#       plugin: "nav2_route::ReroutingService"
#     AdjustSpeedLimit:
#       plugin: "nav2_route::AdjustSpeedLimit"
#     CollisionMonitor:
#       plugin: "nav2_route::CollisionMonitor"
#       max_collision_dist: 3.0
#     edge_cost_functions: ["DistanceScorer", "CostmapScorer"]
#     DistanceScorer:
#       plugin: "nav2_route::DistanceScorer"
#     CostmapScorer:
#       plugin: "nav2_route::CostmapScorer"

# velocity_smoother:
#   ros__parameters:
#     smoothing_frequency: 20.0
#     scale_velocities: False
#     feedback: "OPEN_LOOP"
#     max_velocity: [0.5, 0.0, 2.0]
#     min_velocity: [-0.5, 0.0, -2.0]
#     max_accel: [2.5, 0.0, 3.2]
#     max_decel: [-2.5, 0.0, -3.2]
#     odom_topic: "/<robot_namespace>/odom"
#     odom_duration: 0.1
#     deadband_velocity: [0.0, 0.0, 0.0]
#     velocity_timeout: 1.0

# collision_monitor:
#   ros__parameters:
#     base_frame_id: "<robot_namespace>/base_footprint"
#     odom_frame_id: "<robot_namespace>/odom"
#     cmd_vel_in_topic: "/<robot_namespace>/cmd_vel_smoothed"
#     cmd_vel_out_topic: "/<robot_namespace>/cmd_vel"
#     state_topic: "/<robot_namespace>/collision_monitor_state"
#     transform_tolerance: 2.0
#     source_timeout: 1.0
#     base_shift_correction: True
#     stop_pub_timeout: 2.0
#     # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
#     # and robot footprint for "approach" action type.
#     polygons: ["FootprintApproach"]
#     FootprintApproach:
#       type: "polygon"
#       action_type: "approach"
#       footprint_topic: "/<robot_namespace>/local_costmap/published_footprint"
#       time_before_collision: 1.2
#       simulation_time_step: 0.1
#       min_points: 6
#       visualize: False
#       enabled: True
#     observation_sources: ["scan"]
#     scan:
#       type: "scan"
#       topic: "/<robot_namespace>/scan"
#       min_height: 0.15
#       max_height: 2.0
#       enabled: True

# docking_server:
#   ros__parameters:
#     controller_frequency: 50.0
#     initial_perception_timeout: 5.0
#     wait_charge_timeout: 5.0
#     dock_approach_timeout: 30.0
#     undock_linear_tolerance: 0.05
#     undock_angular_tolerance: 0.1
#     max_retries: 3
#     base_frame: "<robot_namespace>/base_footprint"
#     fixed_frame: "<robot_namespace>/odom"
#     dock_backwards: false
#     dock_prestaging_tolerance: 0.5

#     # Types of docks
#     dock_plugins: ['simple_charging_dock']
#     simple_charging_dock:
#       plugin: 'opennav_docking::SimpleChargingDock'
#       docking_threshold: 0.05
#       staging_x_offset: -0.7
#       use_external_detection_pose: true
#       use_battery_status: false # true
#       use_stall_detection: false # true

#       external_detection_timeout: 1.0
#       external_detection_translation_x: -0.18
#       external_detection_translation_y: 0.0
#       external_detection_rotation_roll: -1.57
#       external_detection_rotation_pitch: -1.57
#       external_detection_rotation_yaw: 0.0
#       filter_coef: 0.1

#     # Dock instances
#     # The following example illustrates configuring dock instances.
#     # docks: ['home_dock']  # Input your docks here
#     # home_dock:
#     #   type: 'simple_charging_dock'
#     #   frame: map
#     #   pose: [0.0, 0.0, 0.0]

#     controller:
#       k_phi: 3.0
#       k_delta: 2.0
#       v_linear_min: 0.15
#       v_linear_max: 0.15
#       use_collision_detection: true
#       costmap_topic: "/<robot_namespace>/local_costmap/costmap_raw"
#       footprint_topic: "/<robot_namespace>/local_costmap/published_footprint"
#       transform_tolerance: 2.0
#       projection_time: 5.0
#       simulation_step: 0.1
#       dock_collision_threshold: 0.3

# loopback_simulator:
#   ros__parameters:
#     base_frame_id: "<robot_namespace>/base_footprint"
#     odom_frame_id: "<robot_namespace>/odom"
#     map_frame_id: "<robot_namespace>/map"
#     scan_frame_id: "<robot_namespace>/base_scan"  # tb4_loopback_simulator.launch.py remaps to 'rplidar_link'
#     update_duration: 0.02
#     scan_range_min: 0.05
#     scan_range_max: 30.0
#     scan_angle_min: -3.1415
#     scan_angle_max: 3.1415
#     scan_angle_increment: 0.02617
#     scan_use_inf: true





